version: "3.8"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: pate
      MYSQL_DATABASE: springdocker
    networks:
      springboot-mysql-net:
  dockercompose:
    container_name: dockercompose
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysqldb
    networks:
      springboot-mysql-net:
    restart: on-failure

networks:
  springboot-mysql-net: